[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  functions = "functions"  # This line is only needed if using serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
